# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decrypt/octodb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x65\x63rypt/octodb.proto\"}\n\x08\x44\x61tabase\x12\x10\n\x08revision\x18\x01 \x01(\x05\x12\x1e\n\x0f\x61ssetBundleList\x18\x02 \x03(\x0b\x32\x05.Data\x12\x0f\n\x07tagname\x18\x03 \x03(\t\x12\x1b\n\x0cresourceList\x18\x04 \x03(\x0b\x32\x05.Data\x12\x11\n\turlFormat\x18\x05 \x01(\t\"\xad\x02\n\x04\x44\x61ta\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilepath\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\x05\x12\x0b\n\x03\x63rc\x18\x05 \x01(\r\x12\x10\n\x08priority\x18\x06 \x01(\x05\x12\r\n\x05tagid\x18\x07 \x03(\x05\x12\x13\n\x0b\x64\x65pendencie\x18\x08 \x03(\x05\x12\x1a\n\x05state\x18\t \x01(\x0e\x32\x0b.Data.State\x12\x0b\n\x03md5\x18\n \x01(\t\x12\x12\n\nobjectName\x18\x0b \x01(\t\x12\x12\n\ngeneration\x18\x0c \x01(\x04\x12\x17\n\x0fuploadVersionId\x18\r \x01(\x05\">\n\x05State\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06LATEST\x10\x03\x12\n\n\x06\x44\x45LETE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'decrypt.octodb_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DATABASE']._serialized_start=24
  _globals['_DATABASE']._serialized_end=149
  _globals['_DATA']._serialized_start=152
  _globals['_DATA']._serialized_end=453
  _globals['_DATA_STATE']._serialized_start=391
  _globals['_DATA_STATE']._serialized_end=453
# @@protoc_insertion_point(module_scope)
